name: transformers
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - numpy=1.19.2
  - pip:
    - transformers==4.19.2
    - scipy==1.9.1
    - matplotlib==3.5.3